In [1]:
#importing required libraries
import pandas as pd
import numpy as np

In [2]:
#importing the dataset
data = pd.read_csv('Problem Statement Dataset.csv')

In [3]:
#viewing the dataset
data.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [4]:
#shape of the data
data.shape

(550068, 12)

In [5]:
#dropping the target variable
data = data.drop('Purchase', axis = 1)

In [6]:
#calculating covariance matrix
Cov_Matrix = data.cov().abs()

In [7]:
Cov_Matrix

User_ID  Occupation  Marital_Status  \
User_ID             2.984573e+06  270.113921       17.367619   
Occupation          2.701139e+02   42.545100        0.077882   
Marital_Status      1.736762e+01    0.077882        0.241838   
Product_Category_1  2.600801e+01    0.195578        0.038497   
Product_Category_2  1.346196e+01    0.012700        0.037819   
Product_Category_3  2.443929e+01    0.354959        0.039400   

                    Product_Category_1  Product_Category_2  Product_Category_3  
User_ID                      26.008008           13.461964           24.439292  
Occupation                    0.195578            0.012700            0.354959  
Marital_Status                0.038497            0.037819            0.039400  
Product_Category_1           15.493760            9.044359            2.438836  
Product_Category_2            9.044359           25.873394           10.092953  
Product_Category_3            2.438836           10.092953           17.018411

In [8]:
#Eigen values and Eigen vectors of covariance matrix
from numpy.linalg import eig
values,vectors=eig(Cov_Matrix)

In [ ]:
#Eigen vectors
vectors

In [10]:
#Eigen values
values

array([2.98457271e+06, 4.25338212e+01, 3.63230993e+01, 2.41439479e-01,
       8.27727055e+00, 1.37718368e+01])

## Selecting the Principal component

* step 1 : Arrange the magnitudes of Eigen values in  Descending

In [27]:
# sorting Eigen values
sorted_val = np.sort(values)

In [28]:
#sorted Eigen values
sorted_val

array([2.41439479e-01, 8.27727055e+00, 1.37718368e+01, 3.63230993e+01,
       4.25338212e+01, 2.98457271e+06])

* step 2: dividing Eigen values by sum of Eigen values

In [31]:
# sum of eigen values
s = sorted_val.sum()

In [32]:
s

2984673.858899531

In [33]:
# each eigen value divded by the sum 's'
v = sorted_val/s

In [35]:
v

array([8.08930858e-08, 2.77325796e-06, 4.61418481e-06, 1.21698722e-05,
       1.42507434e-05, 9.99966111e-01])

In [38]:
#fitting into dataframe
Eigen_values = pd.DataFrame(data = v, index = ['User_ID', 'Occupation', 'Mariatal_Status', 'Product_Category_1', 'Product_Category_2', 'Product_Category_3'])

In [39]:
Eigen_values

0
User_ID             8.089309e-08
Occupation          2.773258e-06
Mariatal_Status     4.614185e-06
Product_Category_1  1.216987e-05
Product_Category_2  1.425074e-05
Product_Category_3  9.999661e-01

'Product_Category_1', 'Product_Category_2' are the two important principal components